# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2915ff88ab80da371c4593c28c6567d801d8b66ed0c6911e48d0934c1614fe9fae4701f16e80ceb5dadcaa8de86ba6d38bfd3b7a79f369e343133a4811a2d093

test:
  secret_key_base: 4ca7ecb930d620fdde37eb86ca316a3f061c3dc3f93d72062f340f069f609ac20b771a2d7213c02f6b5e7520b44dff1909fb3f52a17277933e4ae8d16fbd11b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
